### ISSUE TITLE
Custom Sidebar animation 

### ISSUE THREAD

**Issue by edoardoVD** [arkon/ng-sidebar#50]
Howdy, 

Is there a way to override thee default animation of the sidebar? (it pulls from left to right)

I only see the following on the documentation:
animate	boolean	true	Animate the opening/closing of the sidebar.

I was wondering, since I'm doing some animations using angular2 api

Thanks,
e. Vazquez 😄

**Comment by arkon** [comment]
The animations are done using CSS due to limitations of Angular 2's animations API. If you want to override them, just use plain old CSS to have a different transition!

For reference: https://github.com/arkon/ng-sidebar/blob/master/src/sidebar.component.ts#L74

**Comment by edoardoVD** [comment]
@arkon thanks, I was to set it set it to none or do a custom one with css animations

When you say angular2 animation limitations, what are you referring to ? 
For what I've read and learn angular's 2 framework is using the standard Web Animations API, and there is a recommendation to use a polyfill for older browsers support

Regards,
e. Vazquez

**Comment by arkon** [comment]
I wasn't able to dynamically change the animation state definitions, so I couldn't implement docked mode properly. I was actually using Angular's animation API before, but reverted back to CSS because of that. If they do implement it in the future, I could switch back. We also still saw compatibility issues (#28).
