### ISSUE TITLE
Sidebar not confined to the specific component area

### ISSUE THREAD

**Issue by elega9t** [arkon/ng-sidebar#62]
Hi,

I am trying to get the sidebar working when the header is fixed, and the sidebar is part of the body.

I have divided the page in 2 components, toolbar and body. Sidebar is only wrapping the body component. However when the sidebar is opened, it is rendered on top of the toolbar aswell.

The sample project is available at https://github.com/elega9t/angular-seed-slide-menu

**When Collapsed:**

![sidebar-collapsed](https://cloud.githubusercontent.com/assets/4546883/24582787/44de3d5c-172f-11e7-8060-f09864233dcf.png)

**When Open**
![sidebar-open](https://cloud.githubusercontent.com/assets/4546883/24582786/44d43bc2-172f-11e7-9b07-9e3bd34a7317.png)

**The expected behaviour is:**
![expected-sidebar-open](https://cloud.githubusercontent.com/assets/4546883/24582834/38438754-1730-11e7-83a5-f00f0b903f1e.png)

**Comment by arkon** [comment]
The sidebar's default styling causes it to remain fixed on the body at full height (or width if it's positioned at the top or bottom).

You have a few options:
- Force the sidebar to be positioned some amount from the top so that the toolbar remains visible (but the toolbar would scroll away if it's not fixed as well):
```css
.ng-sidebar--left {
  top: 3em;
}
```
- Position the sidebar absolutely relative to the body container (but it will scroll with the page):
```css
.ng-sidebar {
  position: absolute;
}
```

**Comment by loongdefect** [comment]
Hi arkon,
I try set style in component css as bellow:
`.ng-sidebar--left {`
  `top: 3em;`
}`
but aside not accept style. 
You can help me.

Thank

**Comment by arkon** [comment]
@loongdefect Please refer to [the README](https://github.com/arkon/ng-sidebar#styling).
